fail_fast: false

repos:
  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: ./web-backend/run-pytest.sh
        # entry: pytest ./web-backend/tests/ --maxfail=3 --disable-warnings --collect-only
        language: system
        types: [python]
  - repo: local

    hooks:
      - id: pylint
        name: Running pylint
        entry: pylint --rcfile=./web-backend/pyproject.toml ./web-backend
        language: python
        types: [python]
        stages: [pre-commit]
        files: ^web-backend/.*\.py$
  - repo: local
    hooks:
      - id: ruff
        name: Running ruff with fixing
        entry: ruff --config ./web-backend/pyproject.toml check ./web-backend  # --fix --unsafe-fixes
        language: python
        types: [python]
        stages: [pre-commit]
        files: ^web-backend/.*\.py$
  - repo: local
    hooks:
      - id: prettier
        name: Running prettier
        entry: "cd ./web-react && yarn format"
        # entry: yarn --cwd ./web-react format
        language: system
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: eslint
        name: Running eslint
        entry: "cd ./web-react && yarn eslint --fix"
        # entry: yarn --cwd ./web-react seslint
        language: node
        stages: [pre-commit]
